// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carrito.sql

package dto

import (
	"context"
)

const addToCart = `-- name: AddToCart :exec
INSERT INTO carrito_items (carrito_id, producto_id, cantidad)
VALUES (?, ?, ?)
`

type AddToCartParams struct {
	CarritoID  int32 `json:"carrito_id"`
	ProductoID int32 `json:"producto_id"`
	Cantidad   int32 `json:"cantidad"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) error {
	_, err := q.db.ExecContext(ctx, addToCart, arg.CarritoID, arg.ProductoID, arg.Cantidad)
	return err
}

const createCarrito = `-- name: CreateCarrito :exec
INSERT INTO carrito (usuario_id)
VALUES (?)
`

func (q *Queries) CreateCarrito(ctx context.Context, usuarioID int32) error {
	_, err := q.db.ExecContext(ctx, createCarrito, usuarioID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM carrito_items
WHERE carrito_id = ? AND producto_id = ?
`

type DeleteCartItemParams struct {
	CarritoID  int32 `json:"carrito_id"`
	ProductoID int32 `json:"producto_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteCartItem, arg.CarritoID, arg.ProductoID)
	return err
}

const getAllCarritos = `-- name: GetAllCarritos :many
SELECT 
    c.id AS carrito_id,
    c.usuario_id AS usuario_id
FROM carrito c
`

type GetAllCarritosRow struct {
	CarritoID int32 `json:"carrito_id"`
	UsuarioID int32 `json:"usuario_id"`
}

func (q *Queries) GetAllCarritos(ctx context.Context) ([]GetAllCarritosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCarritos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCarritosRow
	for rows.Next() {
		var i GetAllCarritosRow
		if err := rows.Scan(&i.CarritoID, &i.UsuarioID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarritosByProducto = `-- name: GetCarritosByProducto :many
SELECT 
    ci.carrito_id,
    p.id,
    p.name,
    ci.cantidad
FROM carrito_items ci
JOIN products p ON ci.producto_id = p.id
WHERE p.id = ?
`

type GetCarritosByProductoRow struct {
	CarritoID int32  `json:"carrito_id"`
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Cantidad  int32  `json:"cantidad"`
}

func (q *Queries) GetCarritosByProducto(ctx context.Context, id int32) ([]GetCarritosByProductoRow, error) {
	rows, err := q.db.QueryContext(ctx, getCarritosByProducto, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCarritosByProductoRow
	for rows.Next() {
		var i GetCarritosByProductoRow
		if err := rows.Scan(
			&i.CarritoID,
			&i.ID,
			&i.Name,
			&i.Cantidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarritosByUserV3 = `-- name: GetCarritosByUserV3 :many
SELECT 
    c.id,
    c.usuario_id
FROM carrito c
WHERE c.usuario_id = ?
`

func (q *Queries) GetCarritosByUserV3(ctx context.Context, usuarioID int32) ([]Carrito, error) {
	rows, err := q.db.QueryContext(ctx, getCarritosByUserV3, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrito
	for rows.Next() {
		var i Carrito
		if err := rows.Scan(&i.ID, &i.UsuarioID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItems = `-- name: GetCartItems :many
SELECT 
    ci.carrito_id,
    p.id,
    p.name,
    CAST(p.price AS DECIMAL(10,2)) AS price,
    ci.cantidad
FROM carrito_items ci
JOIN products p ON ci.producto_id = p.id
WHERE ci.carrito_id = ?
`

type GetCartItemsRow struct {
	CarritoID int32  `json:"carrito_id"`
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Price     string `json:"price"`
	Cantidad  int32  `json:"cantidad"`
}

func (q *Queries) GetCartItems(ctx context.Context, carritoID int32) ([]GetCartItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCartItems, carritoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.CarritoID,
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Cantidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
