// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compra.sql

package dto

import (
	"context"
	"database/sql"
)

const createCompra = `-- name: CreateCompra :execresult
INSERT INTO compra (usuario_id, total, estado, fecha)
VALUES (?, ?, ?, NOW())
`

type CreateCompraParams struct {
	UsuarioID sql.NullInt32  `json:"usuario_id"`
	Total     sql.NullString `json:"total"`
	Estado    sql.NullString `json:"estado"`
}

func (q *Queries) CreateCompra(ctx context.Context, arg CreateCompraParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCompra, arg.UsuarioID, arg.Total, arg.Estado)
}

const createDetalleCompra = `-- name: CreateDetalleCompra :exec
INSERT INTO detalle_compra (compra_id, producto_id, cantidad, precio_unitario, subtotal)
VALUES (?, ?, ?, ?, ?)
`

type CreateDetalleCompraParams struct {
	CompraID       int32          `json:"compra_id"`
	ProductoID     int32          `json:"producto_id"`
	Cantidad       int32          `json:"cantidad"`
	PrecioUnitario sql.NullString `json:"precio_unitario"`
	Subtotal       sql.NullString `json:"subtotal"`
}

func (q *Queries) CreateDetalleCompra(ctx context.Context, arg CreateDetalleCompraParams) error {
	_, err := q.db.ExecContext(ctx, createDetalleCompra,
		arg.CompraID,
		arg.ProductoID,
		arg.Cantidad,
		arg.PrecioUnitario,
		arg.Subtotal,
	)
	return err
}

const getAllCompras = `-- name: GetAllCompras :many
SELECT 
    id,
    usuario_id,
    fecha,
    total,
    estado
FROM compra
`

type GetAllComprasRow struct {
	ID        int32          `json:"id"`
	UsuarioID sql.NullInt32  `json:"usuario_id"`
	Fecha     sql.NullTime   `json:"fecha"`
	Total     sql.NullString `json:"total"`
	Estado    sql.NullString `json:"estado"`
}

func (q *Queries) GetAllCompras(ctx context.Context) ([]GetAllComprasRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllComprasRow
	for rows.Next() {
		var i GetAllComprasRow
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Fecha,
			&i.Total,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompraById = `-- name: GetCompraById :one
SELECT 
    id,
    usuario_id,
    fecha,
    total,
    estado
FROM compra
WHERE id = ?
`

type GetCompraByIdRow struct {
	ID        int32          `json:"id"`
	UsuarioID sql.NullInt32  `json:"usuario_id"`
	Fecha     sql.NullTime   `json:"fecha"`
	Total     sql.NullString `json:"total"`
	Estado    sql.NullString `json:"estado"`
}

func (q *Queries) GetCompraById(ctx context.Context, id int32) (GetCompraByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getCompraById, id)
	var i GetCompraByIdRow
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Fecha,
		&i.Total,
		&i.Estado,
	)
	return i, err
}

const getComprasByUser = `-- name: GetComprasByUser :many
SELECT 
    id,
    usuario_id,
    fecha,
    total,
    estado
FROM compra
WHERE usuario_id = ?
`

type GetComprasByUserRow struct {
	ID        int32          `json:"id"`
	UsuarioID sql.NullInt32  `json:"usuario_id"`
	Fecha     sql.NullTime   `json:"fecha"`
	Total     sql.NullString `json:"total"`
	Estado    sql.NullString `json:"estado"`
}

func (q *Queries) GetComprasByUser(ctx context.Context, usuarioID sql.NullInt32) ([]GetComprasByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getComprasByUser, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComprasByUserRow
	for rows.Next() {
		var i GetComprasByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Fecha,
			&i.Total,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDetalleCompra = `-- name: GetDetalleCompra :many
SELECT 
    dc.compra_id,
    p.id,
    p.name,
    dc.precio_unitario,
    dc.cantidad,
    dc.subtotal
FROM detalle_compra dc
JOIN products p ON dc.producto_id = p.id
WHERE dc.compra_id = ?
`

type GetDetalleCompraRow struct {
	CompraID       int32          `json:"compra_id"`
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	PrecioUnitario sql.NullString `json:"precio_unitario"`
	Cantidad       int32          `json:"cantidad"`
	Subtotal       sql.NullString `json:"subtotal"`
}

func (q *Queries) GetDetalleCompra(ctx context.Context, compraID int32) ([]GetDetalleCompraRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetalleCompra, compraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetalleCompraRow
	for rows.Next() {
		var i GetDetalleCompraRow
		if err := rows.Scan(
			&i.CompraID,
			&i.ID,
			&i.Name,
			&i.PrecioUnitario,
			&i.Cantidad,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompraTotal = `-- name: UpdateCompraTotal :exec
UPDATE compra
SET total = ?
WHERE id = ?
`

type UpdateCompraTotalParams struct {
	Total sql.NullString `json:"total"`
	ID    int32          `json:"id"`
}

func (q *Queries) UpdateCompraTotal(ctx context.Context, arg UpdateCompraTotalParams) error {
	_, err := q.db.ExecContext(ctx, updateCompraTotal, arg.Total, arg.ID)
	return err
}
