// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dto

import (
	"database/sql"
)

type Carrito struct {
	ID        int32 `json:"id"`
	UsuarioID int32 `json:"usuario_id"`
}

type CarritoItem struct {
	ID         int32 `json:"id"`
	CarritoID  int32 `json:"carrito_id"`
	ProductoID int32 `json:"producto_id"`
	Cantidad   int32 `json:"cantidad"`
}

type Category struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Compra struct {
	ID        int32          `json:"id"`
	UsuarioID sql.NullInt32  `json:"usuario_id"`
	Total     sql.NullString `json:"total"`
	Estado    sql.NullString `json:"estado"`
	Fecha     sql.NullTime   `json:"fecha"`
}

type DetalleCompra struct {
	ID             int32          `json:"id"`
	CompraID       int32          `json:"compra_id"`
	ProductoID     int32          `json:"producto_id"`
	Cantidad       int32          `json:"cantidad"`
	PrecioUnitario sql.NullString `json:"precio_unitario"`
	Subtotal       sql.NullString `json:"subtotal"`
}

type Product struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       sql.NullString `json:"price"`
	Stock       sql.NullInt32  `json:"stock"`
	CategoryID  int32          `json:"category_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
