version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_libreria
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libreria_suiza_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: api_libreria
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

volumes:
  mysql_data: